server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /orders {
        proxy_pass http://order-service:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /events {
        proxy_pass http://order-service:3001;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header Cache-Control no-cache;
        proxy_buffering off;
        proxy_read_timeout 86400s;
        chunked_transfer_encoding on;
    }

    location /analytics {
        proxy_pass http://analytics-service:3004;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /search {
        proxy_pass http://search-service:3005;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
